### ISSUE TITLE
Create connection timeout doesn't work if redis is not running.

### ISSUE THREAD

**Issue by odv052** [aio-libs/aioredis#598] opened 2019-05-22 15:26 UTC
Hi,
the following traceback raised instantly despite timeout argument. Is it really expected behavior? 
```
Traceback (most recent call last):
  File "/Users/dmitry/Library/Preferences/PyCharm2018.3/scratches/scratch_4.py", line 43, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Users/dmitry/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/dmitry/Library/Preferences/PyCharm2018.3/scratches/scratch_4.py", line 12, in main
    sub = await aioredis.create_redis(('localhost', '6379'), timeout=10)
  File "/Users/dmitry/hopto/gg-server/env/lib/python3.7/site-packages/aioredis/commands/__init__.py", line 178, in create_redis
    loop=loop)
  File "/Users/dmitry/hopto/gg-server/env/lib/python3.7/site-packages/aioredis/connection.py", line 108, in create_connection
    timeout, loop=loop)
  File "/Users/dmitry/.pyenv/versions/3.7.2/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/Users/dmitry/hopto/gg-server/env/lib/python3.7/site-packages/aioredis/stream.py", line 19, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/Users/dmitry/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 968, in create_connection
    ', '.join(str(exc) for exc in exceptions)))
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 6379, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 6379)
```

**Comment by ngood97** [comment] 2019-08-21 18:01
I'm getting the same error when I use this snippet of code:
```
async def redis_pool():
    # Redis client bound to pool of connections (auto-reconnecting).
    redis = await aioredis.create_redis_pool(
        'redis://localhost')
    await redis.set('my-key', 'value')
    val = await redis.get('my-key')
    print(val)

    # gracefully closing underlying connection
    redis.close()
    await redis.wait_closed()


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(redis_pool())
```

Which is a trimmed version from the examples.

How can something that claims to be `(auto-reconnecting)` fail instantly if redis isn't available?

**Comment by popravich** [comment] 2019-10-01 14:11
This is intended behavior.
`timeout` argument is used to limit maximum connection time (for instance, in case of slow network or slow DNS). If we receive error before timeout expire (your cases) — we raise it.

If you really need to start application without / before Redis server you, guys, 
can use `minsize` set to 0:
```python
uninit_redis = await aioredis.create_redis_pool('redis://localhost', minsize=0)
```
This would instantiate Redis client backed by empty connections pool. The connection
process will be initiated on first issued command.

**Closed by popravich** 2019-10-01 14:11 UTC
